#common config
---
spring:
    application:
        name: bookmark
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect 
        show-sql: true       

server:
    port: 9000
  
logging:
    level:
        bookmarks: DEBUG
        org.springframework.web: DEBUG   
      #  org.h2: INFO
      #  org.hibernate: INFO
     
test:
    name:common