#common config
---
spring:
    application:
        name: bookmark
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:tcp://localhost/~/sso
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect 
        show-sql: true       
        hibernate.ddl-auto:create

server:
    port: 9000
  
logging:
    level:
        bookmarks: DEBUG
        org.springframework.web: DEBUG   
      #  org.h2: INFO
      #  org.hibernate: INFO
     
test:
    name:common
#dev evn
---
spring:
    profiles: development
    application:
        name: bookmark

        
server:
    port: 8080

   
logging:
    level:
        bookmarks: DEBUG
        org.springframework.web: DEBUG 
test:
    name: development
    
#production evn
---

spring:
    profiles: production
    application:
        name: bookmark
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:tcp://localhost/~/bookmark
        username: sa
        
server:
    port: 80
          
logging:
    level:
        bookmarks: INFO
        org.springframework.web: INFO

test:
    name: production