#common config
---
spring:
    application:
        name: bookmark
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:tcp://localhost/~/sso
        username: sa
server:
    port: 9000
  
logging:
    level:
        bookmarks: DEBUG
        org.springframework.web: DEBUG   