#common config
---
spring:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect 
        show-sql: true  
        hibernate.ddl-auto: none      
    datasource:
        schema: classpath:config/sql/schema.sql
        data: classpath:config/sql/Group_Role_data.sql

server:
    port: 9000
  
logging:
    level:
        org.springframework.web: DEBUG   
      #  org.h2: INFO
      #  org.hibernate: INFO
     
test:
    name:common
#dev evn
---
spring:
    profiles: development
    application:
        name: bookmark

        
server:
    port: 8080

   
logging:
    level:
        bookmarks: DEBUG
        org.springframework.web: DEBUG 
test:
    name: development
    
#production evn
---

spring:
    profiles: production
    application:
        name: bookmark
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:tcp://localhost/~/bookmark
        username: sa
        
server:
    port: 80
          
logging:
    level:
        bookmarks: INFO
        org.springframework.web: INFO

test:
    name: production