#common config
---
server:
    port: 8080
  
logging:
    level:
        org.springframework:
            web: DEBUG 
            security: DEBUG
      #  org.h2: INFO
      #  org.hibernate: INFO
     
#dev evn
---
spring:
    profiles: development
    application:
        name: common_security
       
logging:
    level:
        org.springframework.web: DEBUG 
    
#production evn
---

spring:
    profiles: production
    application:
        name: bookmark
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:tcp://localhost/~/bookmark
        username: sa
        
server:
    port: 80
          
logging:
    level:
        bookmarks: INFO
        org.springframework.web: INFO

#local Authentication config
---
spring:
    profiles: localDBAuthentication
    
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect 
        show-sql: true  
        hibernate.ddl-auto: none      
    datasource:
        schema: classpath:config/sql/schema.sql
        data: classpath:config/sql/Group_Role_data.sql
       
logging:
    level:
        org.springframework.web: DEBUG 